version: "3.7"
services:
  registry:
    image: registry:2
    volumes:
      - data:/var/lib/registry
    restart: unless-stopped
    networks:
      - traefik-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registry.rule=Host(`registry.dev.launchpad.hu`)"
        - "traefik.http.routers.registry.entrypoints=https"
        - "traefik.http.routers.registry.tls.certresolver=leresolver"
        - "traefik.http.routers.registry.service=registry"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
        - "traefik.http.routers.registry.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$05$$YI8L5CpywtbEevrdhVctIehU.lvHDpE5pg7JBWI8mYVDs6yDxlHzG"

networks:
  traefik-net:
    external: true

volumes:
  data:
